CREATE TABLE kit(
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    createdAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    updatedAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    userId UNIQUEIDENTIFIER,
    status character varying NOT NULL DEFAULT ‘ registered ’,
    dateOfSampleCollection DATETIME,
    dateReceivedByLab DATETIME,
    resultsAvailable date,
    lockStatus character varying,
    pdf character varying,
    taxonomy character varying,
    summary character varying,
    fastq character varying,
    pdfUrl character varying,
    taxonomyUrl character varying,
    summaryUrl character varying,
    fastQUrl character varying,
    kitNumber character varying NOT NULL,
    userPractitionerId UNIQUEIDENTIFIER,
    CONSTRAINT “ UQ_62c5c05ef714df17b40924cee6b ” UNIQUE (kitNumber),
    CONSTRAINT “ PK_5dcdc8fbcdc84c412e7fafaac79 ” PRIMARY KEY (id),
    CONSTRAINT “ FK_455778acf15d799f32d6a412efb ” FOREIGN KEY([userId]) REFERENCES [dbo].[user](id) ON DELETE CASCADE ON UPDATE CASCADE
) CREATE TABLE practitioner(
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    createdAt DATETIME NOT NULL DEFAULT GETDATE(),
    updatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    userId UNIQUEIDENTIFIER,
    practiceName character varying,
    practiceUrl character varying,
    degree character varying,
    status character varying NOT NULL DEFAULT ‘ under - review ’,
    gutTestUse character varying,
    gutTestUsedName character varying,
    practitionerType character varying,
    countryLocation character varying,
    cityLocation character varying,
    CONSTRAINT “ REL_51594f622313b4dc85d7b31cc9 ” UNIQUE (userId),
    CONSTRAINT “ PK_6e23eae1429fc2e897d9eebac42 ” PRIMARY KEY (id),
    CONSTRAINT “ FK_51594f622313b4dc85d7b31cc9a ” FOREIGN KEY([userId]) REFERENCES [dbo].[user](id) ON DELETE CASCADE ON UPDATE CASCADE
) CREATE TABLE [dbo].[user](
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    createdAt DATETIME NOT NULL DEFAULT GETDATE(),
    updatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    firstName character varying,
    lastName character varying,
    email character varying NOT NULL,
    phone character varying,
    password character varying,
    recommended character varying,
    practitionerName character varying,
    practitionerId character varying,
    practitionerEmail character varying,
    awarenessChannel character varying,
    receiveMarketing bit NOT NULL DEFAULT ‘ 0 ’,
    role character varying NOT NULL DEFAULT ‘ user ’,
    strategy character varying NOT NULL DEFAULT ‘ normal ’,
    avatar character varying,
    resetPasswordToken character varying,
    resetPasswordExpire bigint,
    emailVerifiedAt DATETIME,
    CONSTRAINT “ UQ_e12875dfb3b1d92d7d7c5377e22 ” UNIQUE (email),
    CONSTRAINT “ PK_cace4a159ff9f2512dd42373760 ” PRIMARY KEY (id)
) CREATE TABLE email (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    createdAt DATETIME NOT NULL DEFAULT GETDATE(),
    updatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    userId UNIQUEIDENTIFIER,
    title character varying NOT NULL DEFAULT ‘ registered ’,
    message character varying,
    CONSTRAINT “ PK_1e7ed8734ee054ef18002e29b1c ” PRIMARY KEY (id),
    CONSTRAINT “ FK_13e97b4a1d6074fd75ea1bb844e ” FOREIGN KEY([userId]) REFERENCES [dbo].[user](id) ON DELETE CASCADE ON UPDATE CASCADE
) CREATE TABLE support (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    createdAt DATETIME NOT NULL DEFAULT GETDATE(),
    updatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    userId UNIQUEIDENTIFIER,
    subject character varying NOT NULL,
    message character varying,
    CONSTRAINT “ PK_54c6021e6f6912eaaee36b3045d ” PRIMARY KEY(id),
    CONSTRAINT “ FK_0768a9a514d90be0f9d00fd8036 ” FOREIGN KEY([userId]) REFERENCES [dbo].[user](id) ON DELETE CASCADE ON UPDATE CASCADE
)